allowBuilds:
  esbuild: true
patchedDependencies:
  '@octanejs/base-ui@0.1.15': patches/@octanejs%2Fbase-ui@0.1.15.patch
  '@octanejs/motion@0.1.16': patches/@octanejs%2Fmotion@0.1.16.patch
  octane@0.1.17: patches/octane@0.1.17.patch
minimumReleaseAgeExclude:
  - '@octanejs/app-core@0.0.13'
  - '@octanejs/base-ui@0.1.15'
  - '@octanejs/cmdk@0.1.0'
  - '@octanejs/dnd-kit@0.1.12'
  - '@octanejs/floating-ui@0.1.16'
  - '@octanejs/motion@0.1.16'
  - '@octanejs/radix@0.1.16'
  - '@octanejs/sonner@0.1.12'
  - '@octanejs/tanstack-query@0.1.16'
  - '@octanejs/tauri@0.0.0'
  - '@octanejs/tiptap@0.0.11'
  - '@octanejs/vite-plugin@0.1.17'
  - '@octanejs/zustand@0.1.16'
  - '@tsrx/typescript-plugin@0.3.116'
  - octane@0.1.17
