allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@octanejs/app-core@0.0.18'
  - '@octanejs/base-ui@0.1.20'
  - '@octanejs/cmdk@0.1.5'
  - '@octanejs/dnd-kit@0.1.17'
  - '@octanejs/floating-ui@0.1.21'
  - '@octanejs/motion@0.1.21'
  - '@octanejs/radix@0.1.21'
  - '@octanejs/sonner@0.1.17'
  - '@octanejs/tanstack-query@0.1.21'
  - '@octanejs/tauri@0.0.5'
  - '@octanejs/tiptap@0.0.16'
  - '@octanejs/vite-plugin@0.1.22'
  - '@octanejs/zustand@0.1.21'
  - octane@0.1.22
  - '@celados/fff-bin-darwin-arm64@0.10.2-nightly.8a9a970'
  - '@celados/fff-bin-darwin-x64@0.10.2-nightly.8a9a970'
  - '@celados/fff-node@0.10.2-nightly.8a9a970'
